TravisCI Tweak - update bundler before install
The travis CI build for ruby 1.9.3 failed with this error message:

    NoMethodError: undefined method `spec' for nil:NilClass
    An error occurred while installing spark_api (1.3.26), and Bundler
    cannot continue.
    Make sure that `gem install spark_api -v '1.3.26'` succeeds before
    bundling.

Seems like a fair number of people had this problem with ruby 1.9.3 and
bundler 1.7.6, so we'll try the workaround that worked for them.